from __future__ import annotations

import json
from pathlib import Path

import pytest

import utils.coco as coco


class FixedUUID:
    hex = "feedface"


def _json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def test_write_coco_annotations_replaces_symlink_leaves_without_target_write(
    tmp_path: Path, monkeypatch
) -> None:
    root = tmp_path / "dataset"
    root.mkdir()
    outside_final = tmp_path / "outside_final.json"
    outside_tmp = tmp_path / "outside_tmp.json"
    outside_final.write_text('{"external": "final"}', encoding="utf-8")
    outside_tmp.write_text('{"external": "tmp"}', encoding="utf-8")
    output_path = root / "_annotations.coco.json"
    tmp_link = output_path.with_name(f"{output_path.name}.feedface.tmp")
    try:
        output_path.symlink_to(outside_final)
        tmp_link.symlink_to(outside_tmp)
    except OSError as exc:
        pytest.skip(f"symlink unsupported: {exc}")
    monkeypatch.setattr(coco.uuid, "uuid4", lambda: FixedUUID())

    coco._write_coco_annotations_impl(
        output_path,
        dataset_id="sample",
        categories=[{"id": 1, "name": "object"}],
        images=[{"id": 1, "file_name": "a.jpg"}],
        annotations=[],
    )

    assert not output_path.is_symlink()
    assert not tmp_link.exists()
    assert _json(output_path)["info"]["description"] == "sample generated by tator"
    assert _json(outside_final) == {"external": "final"}
    assert _json(outside_tmp) == {"external": "tmp"}


def test_ensure_coco_info_fields_replaces_final_symlink_without_target_write(
    tmp_path: Path, monkeypatch
) -> None:
    root = tmp_path / "dataset"
    root.mkdir()
    outside = tmp_path / "outside.json"
    outside.write_text(
        json.dumps({"images": [], "annotations": [], "categories": []}),
        encoding="utf-8",
    )
    output_path = root / "_annotations.coco.json"
    try:
        output_path.symlink_to(outside)
    except OSError as exc:
        pytest.skip(f"symlink unsupported: {exc}")
    monkeypatch.setattr(coco.uuid, "uuid4", lambda: FixedUUID())

    coco._ensure_coco_info_fields_impl(
        output_path,
        "linked",
        [{"id": 1, "name": "object"}],
    )

    assert not output_path.is_symlink()
    assert _json(output_path)["info"]["description"] == "linked generated by tator"
    assert "info" not in _json(outside)


def test_coco_writer_rejects_symlinked_parent(tmp_path: Path) -> None:
    outside = tmp_path / "outside"
    outside.mkdir()
    linked = tmp_path / "linked"
    try:
        linked.symlink_to(outside, target_is_directory=True)
    except OSError as exc:
        pytest.skip(f"symlink unsupported: {exc}")

    with pytest.raises(RuntimeError, match="coco_output_path_invalid"):
        coco._write_coco_annotations_impl(
            linked / "_annotations.coco.json",
            dataset_id="sample",
            categories=[],
            images=[],
            annotations=[],
        )
